### ISSUE TITLE
not really an issue rather a question

### ISSUE THREAD

**Issue by cleesmith** [mceldeen/aero#1]
I am new to Go (liking it so far) but I'm having trouble understanding:

```
for {
    select {
    case now := <-ticker.C:
        fmt.Printf("go func: 1st select: case now := <-ticker.C: ... now=%T=%v\n", now, now)
        select {
        case l.c <- now:
            fmt.Printf("go func: 2nd select: case l.c <- now: ... l.c=%T=%v\n", l.c, l.c)
        default:
            fmt.Printf("go func: 2nd select: default:\n")
        }
    case <-l.cls:
        fmt.Printf("go func: 1st select: case <-l.cls:\n")
        return
    }
}
```

... I put some print's in there to try and understand what's happening, but I never see `default:`
nor `case <-l.cls:` executed no matter what I set in the call to NewBursty.
Everything does work as expected, but I'm just curious.
I hope you don't mind the question -- thanks for sharing the code.

**Comment by m25n** [comment]
1. About [`default:`](https://github.com/mceldeen/aero/blob/master/ratelimit/ratelimit.go#L60)
   When you specify a `default:` case in a `select` statement, it means the select statement does not block if  any of the channels in the `case`s are not ready to send/receive. The reason this code is necessary is because the `l.c` channel is [buffered](https://gobyexample.com/channel-buffering) in order to acheive "burstiness". When a buffered channel becomes full, it can no longer receive and will block until space opens up in the buffer. If the `default` case were not there, it would potentially behave incorrectly, because the rate limiter _could_ have a burst value of burst + 1 (because of the waiting select statement) so it's better to just throw that value away and continue on.
2. About [`case <-l.cls:`](https://github.com/mceldeen/aero/blob/master/ratelimit/ratelimit.go#L62)
   `l.cls` is a close/cancelation channel used to stop the goroutine it's in (by calling the [`Stop`](https://github.com/mceldeen/aero/blob/master/ratelimit/ratelimit.go#L41) method). The reason for this is because goroutines are not garbage collected. Without this, if you wanted to setup and teardown a bunch of rate limiters during the lifecycle of a long lived program, the goroutines would just keep on spinning thereby creating a resource leak. With it, you can just call `Stop` on the rate limiter and it will kill the goroutine. This is also another reason why I used a default case mentioned in item 1. If [`that select statement`](https://github.com/mceldeen/aero/blob/master/ratelimit/ratelimit.go#L58) was blocked on sending the pulse, it would not be able to receive from the close channel. That select statement could potentially never unblock if the rate limiter wasn't being used anymore which would also be a resource leak.

**Comment by cleesmith** [comment]
Thank you very much for the explanation and the code.
